<a href="https://colab.research.google.com/github/TaranDoebe/Pytorch-Tut/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**



*   A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar to NUmpy Arrays, but full of things that make them work better on GPU's
* default data type of float32
* More suitable for deep learning than a numpy array.




In [1]:
import torch
import numpy as np


# **Lists**

In [3]:
my_list = [[1,2,3,4], [6,7,8,9]]
my_list

[[1, 2, 3, 4], [6, 7, 8, 9]]

# **NP Array**

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.51827944, 0.77397053, 0.04286666, 0.30019428],
       [0.53180743, 0.05598237, 0.6893015 , 0.79718007],
       [0.74352787, 0.71077785, 0.84625605, 0.58999082]])

In [5]:
np1.dtype

dtype('float64')

# **Tensors**

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.8440, -0.2299,  0.2471, -1.1853],
        [-0.4974, -0.2748, -0.8236,  0.1871],
        [ 0.3262, -0.7401,  0.0204,  0.4837]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## Create tensor out of np array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5183, 0.7740, 0.0429, 0.3002],
        [0.5318, 0.0560, 0.6893, 0.7972],
        [0.7435, 0.7108, 0.8463, 0.5900]], dtype=torch.float64)