<a href="https://colab.research.google.com/github/TaranDoebe/Pytorch-Tut/blob/main/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch

In [11]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Reshape and View

my_torch = my_torch.reshape(2,5)
my_torch

# we cant do 2 x 6, --> error

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
# Reshape if we dont know the number of items using -1

my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
## -1 is "by something", so we try to split (10) with (2) x (something)

In [17]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

## -1 slot can change as you see

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch4 = my_torch3.view(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
## view and reshape are very similar, can google it. but reshape is newer

In [21]:
## with reshape and view, they will update

my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [26]:
# what happened to my_torch6 after we changed 5?

my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [27]:
# it has been updated, with reshape and view, the change will get reflected

In [28]:
# Slices

my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch7[7]

tensor(7)

In [30]:
# its not grabbing the number 7 but a tensor scalar of 7. different than num(7)

In [31]:
# Grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [32]:
my_torch8[:,1]


tensor([1, 3, 5, 7, 9])

In [33]:
# what if we want to maintain the shape? return a col

my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])