<a href="https://colab.research.google.com/github/TaranDoebe/Pytorch-Tut/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**
*   Add, Substract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment



In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# addition

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
 # Addition Longhand
 torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
# when use which? doesnt matter. Just style.


In [9]:
#Substrtaction

tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [10]:
# Sub Function

torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [11]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
# Mul longhand

torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [14]:
# Division

tensor_b / tensor_a

# Difference, it converts to a float, because you always have decimal remainders in division

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Div longhand

torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [18]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [19]:
# Exponents / power

torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [20]:
# You can also call the first thing
# Another way to call long hand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [21]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a = tensor_a + tensor_b

# or

tensor_a.add_(tensor_b)

tensor([16, 20, 24, 28])